### ISSUE TITLE
Workflow run failed

### ISSUE THREAD

**Issue by Potat0000** [lucacome/docker-image-update-checker#22]
With latest v1.2.0, I still face a `jq: error (at <stdin>:170): Cannot iterate over null (null)` error.

`DEBUG` has been added and could be found at [here](https://github.com/Potat0000/caddy/actions/runs/4029472063/jobs/6927399974)

Thank you for taking the time to investigate what's going on.

**Comment by lucacome** [comment]
Hi @Potat0000 apparently requesting the "fat manifest" when the container has only one platform results in the API sending whatever it wants. 
The PR linked here should fix this.

**Comment by lucacome** [comment]
Well actually the runners have an old version of `curl` so the changes in the PR don't work...I'll keep working on this

**Comment by devzwf** [comment]
Just posting error here 
```
Run lucacome/docker-image-update-checker@v1.2.0
Run result=$(base=pihole/pihole:latest image=devzwf/pihole-dot-doh:latest platforms=linux/amd[6](https://github.com/devzwf/pihole-dot-doh/actions/runs/4025251534/jobs/6918236624#step:2:7)4 /home/runner/work/_actions/lucacome/docker-image-update-checker/v1.2.0/docker.sh)
  result=$(base=pihole/pihole:latest image=devzwf/pihole-dot-doh:latest platforms=linux/amd64 /home/runner/work/_actions/lucacome/docker-image-update-checker/v1.2.0/docker.sh)
  echo "result=${result}" >>$GITHUB_OUTPUT
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
jq: error (at <stdin>:24[8](https://github.com/devzwf/pihole-dot-doh/actions/runs/4025251534/jobs/6918236624#step:2:9)): Cannot iterate over null (null)
Error: Process completed with exit code 5.
```

**Comment by lucacome** [comment]
I've just pushed a fix to main, if you can confirm that it fixes your problems I'll cut a new release

**Comment by Potat0000** [comment]
Problem has been solved in my situation! Thank you so much!

**Comment by devzwf** [comment]
same here 
Thanks a  lot
