### ISSUE TITLE
getting "true" result on daily schedule of GitHub actions

### ISSUE THREAD

**Issue by ayushifundwave09** [lucacome/docker-image-update-checker#32]
Hello, 
I would like to know one thing by using this tool that   
     
     -  name: Check if an update is available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: nginx:1.21.0
          image: user/app: latest
 
when you check the `base-image` and 'image', what happens exactly behind this?

1) does  it fetch the base image which is written here as `nginx:1.21.0` from the docker hub and get the latest digest of this base image 
2) then it fetches a custom image which is `user/app: latest` and then fetches the base image from this custom image and gets the latest digest of the base image. 
3) then it compares the `base image` digest which it fetches from the docker hub with the `custom-image` base-image digest. 
4) then checks if there is any update available or not. 

Am i correct understanding the flow of this tool?

**Comment by lucacome** [comment]
Hi @ayushifundwave09 

from your example, if `user/app` was built with `FROM nginx:1.21.0` it contains all the layers of `nginx:1.21.0`. This action pulls the manifests of the two images and compares the layers. If the layers in `user/app` don't contain the layers of `nginx:1.21.0` it means that something changed.

Unlike other tools (and forks of this action) it doesn't download the images, but just the small manifest files to compare them.

I hope it helps.
