### ISSUE TITLE
set-output is deprecated

### ISSUE THREAD

**Issue by georg-jung** [lucacome/docker-image-update-checker#6]
When this action runs, one gets a warning:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by rix1337** [comment]
@lucacome  I just proposed a change that has worked in my other repos to alleviate the deprecation notice.
Needs your testing, but should fix this issue.
